# Generated by Django 4.2 on 2023-04-20 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidades', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estrelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Estrelas',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='img_hoteis')),
                ('nome', models.CharField(max_length=150)),
                ('preco', models.FloatField()),
                ('endereco', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=11)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.cidades')),
                ('estrelas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.estrelas')),
            ],
        ),
        migrations.CreateModel(
            name='QuartosHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Agendado'), ('Ca', 'Cancelando'), ('C', 'Cancelado')], default='A', max_length=2)),
                ('dias', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.diasemana')),
                ('horarios', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.horario')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Visitas',
            },
        ),
        migrations.CreateModel(
            name='HotelFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_favorito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='tipo_quarto_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.quartoshotel'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
